name: Nix Flake Check

on: [pull_request]

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v24
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Install Nix Linting and Formatting Tools
        run: nix-env -i statix nixfmt-rfc-style -f '<nixpkgs>'

      - name: Flake update
        run: nix flake update

      - name: Run Statix Lint
        run: statix fix

      - name: Run Nix Format
        run: nix fmt

      - name: Nix Flake Checker
        uses: DeterminateSystems/flake-checker-action@v5

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Auto lint/format
